'use client'
import Head from 'next/head'

export default function FAQ() {
  return (
    <main className="min-h-screen bg-neutral-50 text-neutral-900">
      <Head>
        <title>FAQ — YUTIL Consulting</title>
        <meta name="description" content="Frequently asked questions about YUTIL Consulting services, locations, and how to get in touch." />
        <script type="application/ld+json" dangerouslySetInnerHTML={__html: JSON.stringify({"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What services does YUTIL Consulting provide?", "acceptedAnswer": {"@type": "Answer", "text": "We operate across four pillars: Finance & Accounting Consulting, Real Estate Development, Commodity Trading Advisory, and IT, Risk & Compliance Audit."}}, {"@type": "Question", "name": "Where are you located?", "acceptedAnswer": {"@type": "Answer", "text": "We operate from Portland, Oregon; Dallas, Texas; and Lagos, Nigeria, serving clients globally."}}, {"@type": "Question", "name": "How can I contact you?", "acceptedAnswer": {"@type": "Answer", "text": "Email admin@yutilconsulting.com or toluwafemi@yutil.io, or call +1-516-754-1368. You can also use the contact form on our website."}}, {"@type": "Question", "name": "Do you conduct interim and year\u2011end financial audits?", "acceptedAnswer": {"@type": "Answer", "text": "Yes. Our team supports both interim and year\u2011end audits, including technical accounting research and audit readiness."}}, {"@type": "Question", "name": "Do you handle structured financing and investment strategies?", "acceptedAnswer": {"@type": "Answer", "text": "Yes. We support structured financing, capital planning, and investment strategy advisory within our Finance & Accounting pillar."}}, {"@type": "Question", "name": "What commodities do you support?", "acceptedAnswer": {"@type": "Answer", "text": "We connect buyers and sellers of lithium, zinc, iron ore, gold, lead, copper, copper concentrate, and other raw minerals."}}, {"@type": "Question", "name": "What does your IT, Risk & Compliance Audit service cover?", "acceptedAnswer": {"@type": "Answer", "text": "Independent IT systems reviews, risk assessments, compliance testing, data protection and business continuity controls, led by certified specialists."}}, {"@type": "Question", "name": "How fast do you respond?", "acceptedAnswer": {"@type": "Answer", "text": "We aim to acknowledge new inquiries within one business day and schedule scoping calls within 2\u20133 business days."}}]})} />
      </Head>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-3xl font-semibold tracking-tight">Frequently Asked Questions</h1>
        <div className="mt-8 space-y-6">
          <div><h2 className="text-lg font-semibold">What services does YUTIL Consulting provide?</h2><p className="mt-2 text-sm text-neutral-700">We operate across four pillars: Finance &amp; Accounting Consulting, Real Estate Development, Commodity Trading Advisory, and IT, Risk &amp; Compliance Audit.</p></div><div><h2 className="text-lg font-semibold">Where are you located?</h2><p className="mt-2 text-sm text-neutral-700">We operate from Portland, Oregon; Dallas, Texas; and Lagos, Nigeria, serving clients globally.</p></div><div><h2 className="text-lg font-semibold">How can I contact you?</h2><p className="mt-2 text-sm text-neutral-700">Email admin@yutilconsulting.com or toluwafemi@yutil.io, or call +1-516-754-1368. You can also use the contact form on our website.</p></div><div><h2 className="text-lg font-semibold">Do you conduct interim and year‑end financial audits?</h2><p className="mt-2 text-sm text-neutral-700">Yes. Our team supports both interim and year‑end audits, including technical accounting research and audit readiness.</p></div><div><h2 className="text-lg font-semibold">Do you handle structured financing and investment strategies?</h2><p className="mt-2 text-sm text-neutral-700">Yes. We support structured financing, capital planning, and investment strategy advisory within our Finance &amp; Accounting pillar.</p></div><div><h2 className="text-lg font-semibold">What commodities do you support?</h2><p className="mt-2 text-sm text-neutral-700">We connect buyers and sellers of lithium, zinc, iron ore, gold, lead, copper, copper concentrate, and other raw minerals.</p></div><div><h2 className="text-lg font-semibold">What does your IT, Risk &amp; Compliance Audit service cover?</h2><p className="mt-2 text-sm text-neutral-700">Independent IT systems reviews, risk assessments, compliance testing, data protection and business continuity controls, led by certified specialists.</p></div><div><h2 className="text-lg font-semibold">How fast do you respond?</h2><p className="mt-2 text-sm text-neutral-700">We aim to acknowledge new inquiries within one business day and schedule scoping calls within 2–3 business days.</p></div>
        </div>
      </div>
    </main>
  )
}
